import "./globals.css";
 import {Inconsolata} from 'next/font/google';

import type { Metadata } from "next";
const inconsolata = Inconsolata({subsets: ['latin']});

export const metadata:Metadata = {
  title: "My First Next.js App",
  description: "Generated by Next.js",
  keywords: 'Next.js,React,JavaScript',
}
import Navbar from "../components/Navbar";

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inconsolata.className}>
        <Navbar />
        <main className="max-w-3xl mx-auto py-10">
          {children}
        </main>
          </body>
    </html>
  );
}